// components/reports/pdf/PDFFooter.tsx
import { Text, View, StyleSheet } from "@react-pdf/renderer";

interface PDFFooterProps {
    text?: string;
    pageNumber?: boolean;
}

const styles = StyleSheet.create({
    footer: {
        position: "absolute",
        bottom: 30,
        left: 0,
        right: 0,
        textAlign: "center",
        fontSize: 10,
        color: "#6b7280",
        borderTopWidth: 1,
        borderTopColor: "#e5e7eb",
        paddingTop: 10,
    },
});

export function PDFFooter({ text, pageNumber = true }: PDFFooterProps) {
    const defaultText = "Generated by TD Inventory System";

    return (
        <View style={styles.footer}>
            <Text>{text || defaultText}</Text>
            {pageNumber && (
                <Text
                    render={({ pageNumber: currentPage, totalPages }) =>
                        `${currentPage} / ${totalPages}`
                    }
                    fixed
                />
            )}
        </View>
    );
}