import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useAction } from "convex/react";
import { useState } from "react";
import { Button } from "#/components/ui/button";
import { Input } from "#/components/ui/input";
import { Label } from "#/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "#/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "#/components/ui/select";
import { toast } from "sonner";
import { Loader2, Printer, CheckCircle, XCircle } from "lucide-react";
import { api } from "../../../../../convex/_generated/api";
import AppLayout from "#/layouts/app-layout";

export const Route = createFileRoute("/dashboard/stores/settings/")({
  component: StoreSettingsComponent,
});

interface StoreWithAgent {
  _id: string;
  name: string;
  printAgentId: string | null;
  isActive: boolean;
  phone: string;
  address: string | null;
}

function StoreSettingsComponent() {
  const [selectedStoreId, setSelectedStoreId] = useState<string>("");
  const [agentId, setAgentId] = useState("");
  const [isUpdating, setIsUpdating] = useState(false);
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState<{
    success: boolean;
    message: string;
  } | null>(null);

  const stores = useQuery(api.stores.getAllStoresWithPrintAgents) as StoreWithAgent[] | undefined;
  
  // ✅ Use mutation for updating the agent ID (database operation)
  const updatePrintAgent = useMutation(api.stores.updatePrintAgentId);
  
  // ✅ Use action for testing connection (external API call)
  const testConnection = useAction(api.stores.testPrintConnection);

  const selectedStore = stores?.find((s: StoreWithAgent) => s._id === selectedStoreId);

  const handleUpdateAgent = async () => {
    if (!selectedStoreId || !agentId.trim()) {
      toast.error("Please select a store and enter an agent ID");
      return;
    }

    setIsUpdating(true);
    try {
      await updatePrintAgent({
        storeId: selectedStoreId as any,
        agentId: agentId.trim(),
      });
      toast.success("Printer agent ID updated successfully!");
      setTestResult(null);
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "Failed to update agent ID"
      );
    } finally {
      setIsUpdating(false);
    }
  };

  const handleTestConnection = async () => {
    if (!selectedStoreId) {
      toast.error("Please select a store first");
      return;
    }

    setIsTesting(true);
    setTestResult(null);
    try {
      // ✅ This is an ACTION, not a mutation
      const result = await testConnection({
        storeId: selectedStoreId as any,
      });
      setTestResult({
        success: result.success,
        message: result.success
          ? "Printer is online and ready!"
          : result.error || "Connection failed",
      });
      if (result.success) {
        toast.success("Printer connection test successful!");
      } else {
        toast.error(result.error || "Printer connection test failed");
      }
    } catch (error) {
      setTestResult({
        success: false,
        message: error instanceof Error ? error.message : "Test failed",
      });
      toast.error(
        error instanceof Error ? error.message : "Failed to test connection"
      );
    } finally {
      setIsTesting(false);
    }
  };

  return (
    <AppLayout>
      <div className="container max-w-2xl py-8">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold">Store Printer Settings</h1>
            <p className="text-muted-foreground">
              Configure which printer each store uses for receipts
            </p>
          </div>
          <Printer className="h-8 w-8 text-muted-foreground" />
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Configure Print Agent</CardTitle>
            <CardDescription>
              Each store needs a unique printer agent ID. This ID is generated by
              the Electron till app.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Select Store</Label>
              <Select
                value={selectedStoreId}
                onValueChange={(value: string) => {
                  setSelectedStoreId(value);
                  const store = stores?.find((s: StoreWithAgent) => s._id === value);
                  setAgentId(store?.printAgentId || "");
                  setTestResult(null);
                }}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Choose a store..." />
                </SelectTrigger>
                <SelectContent>
                  {stores?.map((store: StoreWithAgent) => (
                    <SelectItem key={store._id} value={store._id}>
                      {store.name} {!store.isActive && "(Inactive)"}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {selectedStore && (
              <>
                <div className="space-y-2">
                  <Label>Current Agent ID</Label>
                  <div className="p-3 bg-muted rounded-md font-mono text-sm break-all">
                    {selectedStore.printAgentId || "Not configured"}
                  </div>
                </div>

                <div className="space-y-2">
                  <Label>New Agent ID</Label>
                  <Input
                    placeholder="Enter the till's agent ID (e.g., d964ff0d-62a9-4b70-9728-c8ad2b466ae2)"
                    value={agentId}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                      setAgentId(e.target.value)
                    }
                  />
                  <p className="text-sm text-muted-foreground">
                    Find this ID in the Electron till app's Settings tab under
                    "Till ID"
                  </p>
                </div>

                <div className="flex flex-col sm:flex-row gap-3">
                  <Button
                    onClick={handleUpdateAgent}
                    disabled={isUpdating || !agentId.trim()}
                    className="flex-1"
                  >
                    {isUpdating ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Updating...
                      </>
                    ) : (
                      "Update Printer Agent ID"
                    )}
                  </Button>
                  <Button
                    variant="outline"
                    onClick={handleTestConnection}
                    disabled={isTesting || !selectedStore.printAgentId}
                    className="flex-1"
                  >
                    {isTesting ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Testing...
                      </>
                    ) : (
                      "Test Connection"
                    )}
                  </Button>
                </div>

                {testResult && (
                  <div
                    className={`p-3 rounded-md flex items-center gap-2 ${
                      testResult.success
                        ? "bg-green-50 text-green-700"
                        : "bg-red-50 text-red-700"
                    }`}
                  >
                    {testResult.success ? (
                      <CheckCircle className="h-4 w-4" />
                    ) : (
                      <XCircle className="h-4 w-4" />
                    )}
                    <span className="text-sm">{testResult.message}</span>
                  </div>
                )}
              </>
            )}
          </CardContent>
        </Card>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle>How to get the Agent ID</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <ol className="list-decimal list-inside space-y-2">
              <li>Open the Electron till application on your POS computer</li>
              <li>Navigate to the Settings tab</li>
              <li>Look for "Till ID" or "Agent ID"</li>
              <li>
                Copy the UUID (e.g., d964ff0d-62a9-4b70-9728-c8ad2b466ae2)
              </li>
              <li>Paste it into the field above and click Update</li>
            </ol>
            <div className="mt-4 p-3 bg-muted rounded-md">
              <p className="font-medium">Troubleshooting:</p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground mt-1">
                <li>Ensure the Electron app is running on the POS computer</li>
                <li>
                  Check that the relay service is accessible from the Electron
                  app
                </li>
                <li>
                  Verify the agent ID is exactly as shown in the Electron app
                  settings
                </li>
                <li>Use the "Test Connection" button to verify connectivity</li>
              </ul>
            </div>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}