/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTransfersIndexRouteImport } from './routes/dashboard/transfers/index'
import { Route as DashboardStoresIndexRouteImport } from './routes/dashboard/stores/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSalesIndexRouteImport } from './routes/dashboard/sales/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardInvoiceIndexRouteImport } from './routes/dashboard/invoice/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/dashboard/inventory/index'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard/employees/index'
import { Route as DashboardDepartmentsIndexRouteImport } from './routes/dashboard/departments/index'
import { Route as DashboardCustomersIndexRouteImport } from './routes/dashboard/customers/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardSettingsPasswordRouteImport } from './routes/dashboard/settings/password'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/dashboard/settings/appearance'
import { Route as DashboardStoresSettingsIndexRouteImport } from './routes/dashboard/stores/settings/index'
import { Route as DashboardProductsExportIndexRouteImport } from './routes/dashboard/products/export/index'
import { Route as DashboardInvoiceNewIndexRouteImport } from './routes/dashboard/invoice/new/index'
import { Route as DashboardInvoiceIdIndexRouteImport } from './routes/dashboard/invoice/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/dashboard/users/',
  path: '/dashboard/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransfersIndexRoute = DashboardTransfersIndexRouteImport.update({
  id: '/dashboard/transfers/',
  path: '/dashboard/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoresIndexRoute = DashboardStoresIndexRouteImport.update({
  id: '/dashboard/stores/',
  path: '/dashboard/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/dashboard/settings/',
  path: '/dashboard/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSalesIndexRoute = DashboardSalesIndexRouteImport.update({
  id: '/dashboard/sales/',
  path: '/dashboard/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/dashboard/reports/',
  path: '/dashboard/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/dashboard/products/',
  path: '/dashboard/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvoiceIndexRoute = DashboardInvoiceIndexRouteImport.update({
  id: '/dashboard/invoice/',
  path: '/dashboard/invoice/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/dashboard/inventory/',
  path: '/dashboard/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/dashboard/employees/',
  path: '/dashboard/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDepartmentsIndexRoute =
  DashboardDepartmentsIndexRouteImport.update({
    id: '/dashboard/departments/',
    path: '/dashboard/departments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/dashboard/customers/',
  path: '/dashboard/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/dashboard/categories/',
    path: '/dashboard/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsPasswordRoute =
  DashboardSettingsPasswordRouteImport.update({
    id: '/dashboard/settings/password',
    path: '/dashboard/settings/password',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/dashboard/settings/appearance',
    path: '/dashboard/settings/appearance',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardStoresSettingsIndexRoute =
  DashboardStoresSettingsIndexRouteImport.update({
    id: '/dashboard/stores/settings/',
    path: '/dashboard/stores/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProductsExportIndexRoute =
  DashboardProductsExportIndexRouteImport.update({
    id: '/dashboard/products/export/',
    path: '/dashboard/products/export/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardInvoiceNewIndexRoute =
  DashboardInvoiceNewIndexRouteImport.update({
    id: '/dashboard/invoice/new/',
    path: '/dashboard/invoice/new/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardInvoiceIdIndexRoute = DashboardInvoiceIdIndexRouteImport.update({
  id: '/dashboard/invoice/$id/',
  path: '/dashboard/invoice/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pos/': typeof PosIndexRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/password': typeof DashboardSettingsPasswordRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/invoice/': typeof DashboardInvoiceIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/sales/': typeof DashboardSalesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/stores/': typeof DashboardStoresIndexRoute
  '/dashboard/transfers/': typeof DashboardTransfersIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/invoice/$id/': typeof DashboardInvoiceIdIndexRoute
  '/dashboard/invoice/new/': typeof DashboardInvoiceNewIndexRoute
  '/dashboard/products/export/': typeof DashboardProductsExportIndexRoute
  '/dashboard/stores/settings/': typeof DashboardStoresSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/pos': typeof PosIndexRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/password': typeof DashboardSettingsPasswordRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/dashboard/departments': typeof DashboardDepartmentsIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/invoice': typeof DashboardInvoiceIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/sales': typeof DashboardSalesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/stores': typeof DashboardStoresIndexRoute
  '/dashboard/transfers': typeof DashboardTransfersIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/invoice/$id': typeof DashboardInvoiceIdIndexRoute
  '/dashboard/invoice/new': typeof DashboardInvoiceNewIndexRoute
  '/dashboard/products/export': typeof DashboardProductsExportIndexRoute
  '/dashboard/stores/settings': typeof DashboardStoresSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pos/': typeof PosIndexRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/password': typeof DashboardSettingsPasswordRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/invoice/': typeof DashboardInvoiceIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/sales/': typeof DashboardSalesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/stores/': typeof DashboardStoresIndexRoute
  '/dashboard/transfers/': typeof DashboardTransfersIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/invoice/$id/': typeof DashboardInvoiceIdIndexRoute
  '/dashboard/invoice/new/': typeof DashboardInvoiceNewIndexRoute
  '/dashboard/products/export/': typeof DashboardProductsExportIndexRoute
  '/dashboard/stores/settings/': typeof DashboardStoresSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/'
    | '/pos/'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/password'
    | '/dashboard/categories/'
    | '/dashboard/customers/'
    | '/dashboard/departments/'
    | '/dashboard/employees/'
    | '/dashboard/inventory/'
    | '/dashboard/invoice/'
    | '/dashboard/products/'
    | '/dashboard/reports/'
    | '/dashboard/sales/'
    | '/dashboard/settings/'
    | '/dashboard/stores/'
    | '/dashboard/transfers/'
    | '/dashboard/users/'
    | '/dashboard/invoice/$id/'
    | '/dashboard/invoice/new/'
    | '/dashboard/products/export/'
    | '/dashboard/stores/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/pos'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/password'
    | '/dashboard/categories'
    | '/dashboard/customers'
    | '/dashboard/departments'
    | '/dashboard/employees'
    | '/dashboard/inventory'
    | '/dashboard/invoice'
    | '/dashboard/products'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/stores'
    | '/dashboard/transfers'
    | '/dashboard/users'
    | '/dashboard/invoice/$id'
    | '/dashboard/invoice/new'
    | '/dashboard/products/export'
    | '/dashboard/stores/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/dashboard/'
    | '/pos/'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/password'
    | '/dashboard/categories/'
    | '/dashboard/customers/'
    | '/dashboard/departments/'
    | '/dashboard/employees/'
    | '/dashboard/inventory/'
    | '/dashboard/invoice/'
    | '/dashboard/products/'
    | '/dashboard/reports/'
    | '/dashboard/sales/'
    | '/dashboard/settings/'
    | '/dashboard/stores/'
    | '/dashboard/transfers/'
    | '/dashboard/users/'
    | '/dashboard/invoice/$id/'
    | '/dashboard/invoice/new/'
    | '/dashboard/products/export/'
    | '/dashboard/stores/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsPasswordRoute: typeof DashboardSettingsPasswordRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
  DashboardDepartmentsIndexRoute: typeof DashboardDepartmentsIndexRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardInvoiceIndexRoute: typeof DashboardInvoiceIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardSalesIndexRoute: typeof DashboardSalesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardStoresIndexRoute: typeof DashboardStoresIndexRoute
  DashboardTransfersIndexRoute: typeof DashboardTransfersIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardInvoiceIdIndexRoute: typeof DashboardInvoiceIdIndexRoute
  DashboardInvoiceNewIndexRoute: typeof DashboardInvoiceNewIndexRoute
  DashboardProductsExportIndexRoute: typeof DashboardProductsExportIndexRoute
  DashboardStoresSettingsIndexRoute: typeof DashboardStoresSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transfers/': {
      id: '/dashboard/transfers/'
      path: '/dashboard/transfers'
      fullPath: '/dashboard/transfers/'
      preLoaderRoute: typeof DashboardTransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stores/': {
      id: '/dashboard/stores/'
      path: '/dashboard/stores'
      fullPath: '/dashboard/stores/'
      preLoaderRoute: typeof DashboardStoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sales/': {
      id: '/dashboard/sales/'
      path: '/dashboard/sales'
      fullPath: '/dashboard/sales/'
      preLoaderRoute: typeof DashboardSalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invoice/': {
      id: '/dashboard/invoice/'
      path: '/dashboard/invoice'
      fullPath: '/dashboard/invoice/'
      preLoaderRoute: typeof DashboardInvoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/dashboard/inventory'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/dashboard/employees'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/departments/': {
      id: '/dashboard/departments/'
      path: '/dashboard/departments'
      fullPath: '/dashboard/departments/'
      preLoaderRoute: typeof DashboardDepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customers/': {
      id: '/dashboard/customers/'
      path: '/dashboard/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/dashboard/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/password': {
      id: '/dashboard/settings/password'
      path: '/dashboard/settings/password'
      fullPath: '/dashboard/settings/password'
      preLoaderRoute: typeof DashboardSettingsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/dashboard/settings/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stores/settings/': {
      id: '/dashboard/stores/settings/'
      path: '/dashboard/stores/settings'
      fullPath: '/dashboard/stores/settings/'
      preLoaderRoute: typeof DashboardStoresSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/export/': {
      id: '/dashboard/products/export/'
      path: '/dashboard/products/export'
      fullPath: '/dashboard/products/export/'
      preLoaderRoute: typeof DashboardProductsExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invoice/new/': {
      id: '/dashboard/invoice/new/'
      path: '/dashboard/invoice/new'
      fullPath: '/dashboard/invoice/new/'
      preLoaderRoute: typeof DashboardInvoiceNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invoice/$id/': {
      id: '/dashboard/invoice/$id/'
      path: '/dashboard/invoice/$id'
      fullPath: '/dashboard/invoice/$id/'
      preLoaderRoute: typeof DashboardInvoiceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PosIndexRoute: PosIndexRoute,
  DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
  DashboardSettingsPasswordRoute: DashboardSettingsPasswordRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
  DashboardDepartmentsIndexRoute: DashboardDepartmentsIndexRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardInvoiceIndexRoute: DashboardInvoiceIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardSalesIndexRoute: DashboardSalesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardStoresIndexRoute: DashboardStoresIndexRoute,
  DashboardTransfersIndexRoute: DashboardTransfersIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardInvoiceIdIndexRoute: DashboardInvoiceIdIndexRoute,
  DashboardInvoiceNewIndexRoute: DashboardInvoiceNewIndexRoute,
  DashboardProductsExportIndexRoute: DashboardProductsExportIndexRoute,
  DashboardStoresSettingsIndexRoute: DashboardStoresSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
